default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: maoct_development

test:
  <<: *default
  database: maoct_test

production:
  <<: *default
  database: maoct
